from pybboxes.boxes.albumentations_bounding_box import AlbumentationsBoundingBox
from pybboxes.boxes.bbox import BoundingBox
from pybboxes.boxes.coco_bounding_box import CocoBoundingBox
from pybboxes.boxes.fiftyone_bounding_box import FiftyoneBoundingBox
from pybboxes.boxes.voc_bounding_box import VocBoundingBox
from pybboxes.boxes.yolo_bounding_box import YoloBoundingBox
