from pybboxes.types.albumentations_bounding_box import AlbumentationsBoundingBox
from pybboxes.types.bbox import BoundingBox
from pybboxes.types.coco_bounding_box import CocoBoundingBox
from pybboxes.types.fiftyone_bounding_box import FiftyoneBoundingBox
from pybboxes.types.voc_bounding_box import VocBoundingBox
from pybboxes.types.yolo_bounding_box import YoloBoundingBox
